/**
 * Shared Excel export standards for MKT HQ v1.0.
 * Read-only helpers — never write to DB or mutate business data.
 */
import type ExcelJS from "exceljs";
import { APP_VERSION } from "@/lib/constants";

export const EXPORT_GENERATED_BY = "MKT HQ";
export const EXPORT_VERSION_LABEL = "MKT HQ v1.0";

/** Soft header styling (readable, not flashy). */
export const EXPORT_HEADER_FILL = "FFF3F4F6";
export const EXPORT_HEADER_FONT = "FF1F2937";
export const EXPORT_ACCENT = "FF7A1F2B";

export interface ExportDateParts {
  datePart: string;
  timePart: string;
  display: string;
  iso: string;
}

export function getExportDateParts(date = new Date()): ExportDateParts {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  const hh = String(date.getHours()).padStart(2, "0");
  const mm = String(date.getMinutes()).padStart(2, "0");
  return {
    datePart: `${y}${m}${d}`,
    timePart: `${hh}${mm}`,
    display: date.toLocaleString(),
    iso: date.toISOString(),
  };
}

export function sanitizeExportFileName(name: string, max = 40): string {
  const cleaned = name
    .trim()
    .replace(/[<>:"/\\|?*\u0000-\u001f]/g, "")
    .replace(/\s+/g, "_")
    .slice(0, max);
  return cleaned || "Untitled";
}

/** MKT_HQ_Product_Export_YYYYMMDD_HHMM.xlsx */
export function buildProductExportFileName(date = new Date()): string {
  const { datePart, timePart } = getExportDateParts(date);
  return `MKT_HQ_Product_Export_${datePart}_${timePart}.xlsx`;
}

/** MKT_HQ_Supplier_Export_YYYYMMDD_HHMM.xlsx */
export function buildSupplierExportFileName(date = new Date()): string {
  const { datePart, timePart } = getExportDateParts(date);
  return `MKT_HQ_Supplier_Export_${datePart}_${timePart}.xlsx`;
}

/** MKT_HQ_Sales_Plan_{ProjectName}_YYYYMMDD.xlsx */
export function buildSalesPlanExportFileName(
  projectName: string,
  date = new Date(),
): string {
  const { datePart } = getExportDateParts(date);
  return `MKT_HQ_Sales_Plan_${sanitizeExportFileName(projectName)}_${datePart}.xlsx`;
}

/** MKT_HQ_Backup_YYYYMMDD_HHMM.xlsx */
export function buildBackupExportFileName(date = new Date()): string {
  const { datePart, timePart } = getExportDateParts(date);
  return `MKT_HQ_Backup_${datePart}_${timePart}.xlsx`;
}

export function buildComparisonExportFileName(date = new Date()): string {
  const { datePart, timePart } = getExportDateParts(date);
  return `MKT_HQ_Sales_Plan_Comparison_${datePart}_${timePart}.xlsx`;
}

/** Safe cell value — never throws on missing/odd data. */
export function exportCell(value: unknown): string | number | boolean {
  if (value == null) return "";
  if (typeof value === "string") return value;
  if (typeof value === "number") {
    return Number.isFinite(value) ? value : "";
  }
  if (typeof value === "boolean") return value;
  if (value instanceof Date) {
    return Number.isNaN(value.getTime()) ? "" : value.toISOString();
  }
  try {
    return String(value);
  } catch {
    return "";
  }
}

/** Percent points (e.g. 42) → Excel fraction for 0.00% format. */
export function exportPercentPoints(value: unknown): number | "" {
  const n = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(n)) return "";
  return n / 100;
}

export function applyWorkbookIdentity(
  workbook: ExcelJS.Workbook,
  title: string,
  date = new Date(),
): void {
  workbook.creator = EXPORT_GENERATED_BY;
  workbook.lastModifiedBy = EXPORT_GENERATED_BY;
  workbook.created = date;
  workbook.modified = date;
  workbook.title = title;
  workbook.description = `${title} · ${EXPORT_VERSION_LABEL}`;
}

export function styleExportHeader(row: ExcelJS.Row): void {
  row.font = { bold: true, color: { argb: EXPORT_HEADER_FONT }, size: 11 };
  row.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: EXPORT_HEADER_FILL },
  };
  row.alignment = { vertical: "middle", wrapText: true };
  row.height = 22;
}

export function addExportMetaSheet(
  workbook: ExcelJS.Workbook,
  title: string,
  extra: Array<[string, string | number]> = [],
  date = new Date(),
): ExcelJS.Worksheet {
  const parts = getExportDateParts(date);
  const sheet = workbook.addWorksheet("_Meta");
  sheet.getColumn(1).width = 28;
  sheet.getColumn(2).width = 52;

  sheet.getCell("A1").value = title;
  sheet.getCell("A1").font = {
    bold: true,
    size: 14,
    color: { argb: EXPORT_ACCENT },
  };

  const rows: Array<[string, string | number]> = [
    ["Generated by", EXPORT_GENERATED_BY],
    ["Generated date/time", parts.display],
    ["Version", EXPORT_VERSION_LABEL],
    ["App version constant", APP_VERSION],
    ["Mode", "Read-only export (no database changes)"],
    ...extra,
  ];

  rows.forEach(([label, value], index) => {
    const row = index + 3;
    sheet.getCell(`A${row}`).value = label;
    sheet.getCell(`A${row}`).font = { bold: true, color: { argb: "FF4B5563" } };
    sheet.getCell(`B${row}`).value = value;
  });

  return sheet;
}

export function finalizeDataSheet(
  sheet: ExcelJS.Worksheet,
  options?: {
    priceColumns?: number[];
    percentColumns?: number[];
    moqColumns?: number[];
    minWidth?: number;
    maxWidth?: number;
  },
): void {
  const headerRow = sheet.getRow(1);
  const colCount = headerRow.cellCount;
  if (colCount === 0) return;

  const minWidth = options?.minWidth ?? 10;
  const maxWidth = options?.maxWidth ?? 40;

  for (let col = 1; col <= colCount; col++) {
    const header = String(headerRow.getCell(col).value ?? "");
    let width = Math.min(Math.max(header.length + 2, minWidth), maxWidth);

    for (let r = 2; r <= Math.min(sheet.rowCount, 80); r++) {
      const text = String(sheet.getRow(r).getCell(col).value ?? "");
      width = Math.min(Math.max(width, Math.min(text.length + 2, maxWidth)), maxWidth);
    }
    sheet.getColumn(col).width = width;
  }

  const priceCols = options?.priceColumns ?? [];
  const percentCols = options?.percentColumns ?? [];
  const moqCols = options?.moqColumns ?? [];

  for (let r = 2; r <= sheet.rowCount; r++) {
    const row = sheet.getRow(r);
    for (const col of priceCols) {
      row.getCell(col).numFmt = "#,##0";
    }
    for (const col of moqCols) {
      row.getCell(col).numFmt = "#,##0";
    }
    for (const col of percentCols) {
      row.getCell(col).numFmt = "0.00%";
    }
  }

  sheet.views = [{ state: "frozen", ySplit: 1 }];
  if (sheet.rowCount >= 1 && colCount >= 1) {
    sheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: Math.max(sheet.rowCount, 1), column: colCount },
    };
  }
}

export async function downloadWorkbook(
  workbook: ExcelJS.Workbook,
  fileName: string,
): Promise<void> {
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
