import type { ProductIdea } from "@/types/idea";

export const IDEA_SEEDS: ProductIdea[] = [
  {
    id: "idea-001",
    productName: "Ultrasonic Jewelry Cleaner Mini",
    sourceLink: "https://www.alibaba.com/product-detail/ultrasonic-jewelry-cleaner",
    sourcePlatform: "alibaba",
    imageUrl: null,
    whyInteresting:
      "Compact form factor fits FTI Lifestyle gift sets. Strong margin potential in mall channels.",
    possibleBrand: "Variia",
    estimatedPriceRange: "฿890 – ฿1,490",
    tags: ["lifestyle", "gift", "compact"],
    status: "interested",
    convertedProductId: null,
    createdAt: "2026-07-01T10:00:00",
    updatedAt: "2026-07-02T14:30:00",
  },
  {
    id: "idea-002",
    productName: "Foldable Mini Washing Machine",
    sourceLink: "https://detail.1688.com/offer/foldable-mini-washer",
    sourcePlatform: "1688",
    imageUrl: null,
    whyInteresting:
      "Dorm and condo trend in Bangkok. Competitors weak on branding — room for Aquatek entry.",
    possibleBrand: "Aquatek",
    estimatedPriceRange: "฿2,500 – ฿4,200",
    tags: ["appliances", "dorm", "aquatek"],
    status: "shortlisted",
    convertedProductId: null,
    createdAt: "2026-06-28T09:15:00",
    updatedAt: "2026-07-01T11:00:00",
  },
  {
    id: "idea-003",
    productName: "Smart Pet Feeder with Camera",
    sourceLink: "https://www.tiktok.com/shop/smart-pet-feeder-wifi",
    sourcePlatform: "tiktok",
    imageUrl: null,
    whyInteresting:
      "Pet economy growing fast in TH. App-connected feeders trending on social commerce.",
    possibleBrand: "Fastpure",
    estimatedPriceRange: "฿1,800 – ฿3,500",
    tags: ["pet", "smart home", "wifi"],
    status: "interested",
    convertedProductId: null,
    createdAt: "2026-07-02T08:00:00",
    updatedAt: "2026-07-02T08:00:00",
  },
  {
    id: "idea-004",
    productName: "RGB LED Strip Kit (Generic)",
    sourceLink: "https://shopee.co.th/rgb-led-strip-kit",
    sourcePlatform: "shopee",
    imageUrl: null,
    whyInteresting:
      "High volume but saturated market. Margin too thin for FTI private label.",
    possibleBrand: "—",
    estimatedPriceRange: "฿199 – ฿399",
    tags: ["lighting", "commodity"],
    status: "rejected",
    convertedProductId: null,
    createdAt: "2026-06-20T16:00:00",
    updatedAt: "2026-06-25T10:00:00",
  },
  {
    id: "idea-005",
    productName: "Portable Clothes Steamer Pro",
    sourceLink: "https://www.amazon.com/portable-clothes-steamer",
    sourcePlatform: "amazon",
    imageUrl: null,
    whyInteresting:
      "Travel segment rebounding. Good fit for Treatton travel line with OEM customization.",
    possibleBrand: "Treatton",
    estimatedPriceRange: "฿1,200 – ฿2,100",
    tags: ["travel", "garment care", "treatton"],
    status: "interested",
    convertedProductId: null,
    createdAt: "2026-06-30T13:45:00",
    updatedAt: "2026-07-03T09:00:00",
  },
  {
    id: "idea-006",
    productName: "Robot Window Cleaner",
    sourceLink: "https://www.made-in-china.com/robot-window-cleaner",
    sourcePlatform: "made_in_china",
    imageUrl: null,
    whyInteresting:
      "High-rise condo demand in BKK. Saw viral demo — needs factory validation.",
    possibleBrand: "Uni-Pure",
    estimatedPriceRange: "฿4,500 – ฿8,900",
    tags: ["smart home", "cleaning", "premium"],
    status: "shortlisted",
    convertedProductId: null,
    createdAt: "2026-06-15T11:30:00",
    updatedAt: "2026-06-29T15:20:00",
  },
];
