import { createSupplier } from "@/lib/supplier-builder";

const supplierSeeds = [
  createSupplier({
    id: "sup-001",
    factoryName: "Guangzhou CleanTech Co.",
    displayName: "CleanTech Guangzhou",
    country: "China",
    provinceRegion: "Guangdong",
    cityDistrict: "Guangzhou · Panyu",
    fullAddress: "No. 88 Industrial Park Rd, Panyu District, Guangzhou",
    locationNote: "15 min from Guangzhou South Railway Station",
    website: "https://cleantech-gz.example.com",
    alibabaLink: "https://cleantech.en.alibaba.com",
    mainProductCategory: "Air Purifiers & HVAC",
    notes: "Strong OEM partner for HEPA products. ISO 9001 certified.",
    updatedAt: "2026-07-02T09:30:00",
    contacts: [
      {
        contactName: "Lin Wei",
        position: "Sales Manager",
        salesRepCode: "CT-042",
        wechatId: "linwei_cleantech",
        whatsapp: "+86 138 0013 8001",
        phone: "+86 20 8888 1234",
        email: "lin@cleantech.cn",
        line: "",
        isPrimary: true,
        isActive: true,
        notes: "Primary contact for FTI air purifier line",
      },
    ],
  }),
  createSupplier({
    id: "sup-002",
    factoryName: "Shenzhen BlendWorks Ltd.",
    displayName: "BlendWorks",
    country: "China",
    provinceRegion: "Guangdong",
    cityDistrict: "Shenzhen · Bao'an",
    fullAddress: "Building 3, Tech Park, Bao'an, Shenzhen",
    alibabaLink: "https://blendworks.en.alibaba.com",
    mainProductCategory: "Small Kitchen Appliances",
    updatedAt: "2026-07-01T14:15:00",
    contacts: [
      {
        contactName: "Chen Hao",
        position: "Export Sales",
        salesRepCode: "BW-118",
        wechatId: "chenhao_blend",
        whatsapp: "+86 139 0013 9002",
        phone: "+86 755 2888 5678",
        email: "sales@blendworks.com",
        line: "",
        isPrimary: true,
        isActive: true,
        notes: "",
      },
    ],
  }),
  createSupplier({
    id: "sup-003",
    factoryName: "Hangzhou PureFlow Inc.",
    displayName: "PureFlow Hangzhou",
    country: "China",
    provinceRegion: "Zhejiang",
    cityDistrict: "Hangzhou · Binjiang",
    mainProductCategory: "Water Filtration",
    alibabaLink: "https://pureflow.en.alibaba.com",
    updatedAt: "2026-06-30T11:00:00",
    contacts: [
      {
        contactName: "Wang Mei",
        position: "Account Manager",
        salesRepCode: "PF-033",
        wechatId: "wangmei_pureflow",
        whatsapp: "",
        phone: "+86 571 8888 9012",
        email: "mei@pureflow.cn",
        line: "",
        isPrimary: true,
        isActive: true,
        notes: "",
      },
    ],
  }),
  createSupplier({
    id: "sup-004",
    factoryName: "Ningbo HomePro Mfg.",
    displayName: "HomePro Ningbo",
    country: "China",
    provinceRegion: "Zhejiang",
    cityDistrict: "Ningbo · Beilun",
    mainProductCategory: "Home Appliances",
    updatedAt: "2026-06-29T16:45:00",
    contacts: [
      {
        contactName: "Zhang Lei",
        position: "Sales Director",
        salesRepCode: "HP-207",
        wechatId: "zhanglei_homepro",
        whatsapp: "+86 137 0013 7004",
        phone: "+86 574 8888 3456",
        email: "lei@homepro-mfg.com",
        line: "",
        isPrimary: true,
        isActive: true,
        notes: "",
      },
    ],
  }),
  createSupplier({
    id: "sup-005",
    factoryName: "Shenzhen SecureHome Tech",
    displayName: "SecureHome",
    country: "China",
    provinceRegion: "Guangdong",
    cityDistrict: "Shenzhen · Longhua",
    mainProductCategory: "Smart Home & Security",
    updatedAt: "2026-06-28T10:20:00",
    contacts: [
      {
        contactName: "Liu Yang",
        position: "BD Manager",
        salesRepCode: "SH-091",
        wechatId: "liuyang_secure",
        whatsapp: "",
        phone: "+86 755 2888 7890",
        email: "yang@securehome.tech",
        line: "",
        isPrimary: true,
        isActive: true,
        notes: "",
      },
    ],
  }),
  createSupplier({
    id: "sup-006",
    factoryName: "Dongguan VisionDrive Co.",
    displayName: "VisionDrive",
    country: "China",
    provinceRegion: "Guangdong",
    cityDistrict: "Dongguan · Chang'an",
    mainProductCategory: "Automotive Electronics",
    updatedAt: "2026-07-02T08:00:00",
    contacts: [
      {
        contactName: "Huang Jie",
        position: "Sales Rep",
        salesRepCode: "VD-156",
        wechatId: "huangjie_vd",
        whatsapp: "+86 136 0013 6006",
        phone: "+86 769 8888 2345",
        email: "jie@visiondrive.cn",
        line: "",
        isPrimary: true,
        isActive: true,
        notes: "",
      },
    ],
  }),
  createSupplier({
    id: "sup-007",
    factoryName: "Xiamen RecoverTech Ltd.",
    displayName: "RecoverTech",
    country: "China",
    provinceRegion: "Fujian",
    cityDistrict: "Xiamen · Huli",
    mainProductCategory: "Health & Wellness",
    updatedAt: "2026-06-15T09:00:00",
    contacts: [
      {
        contactName: "Wu Xia",
        position: "Export Sales",
        salesRepCode: "RT-044",
        wechatId: "wuxia_recover",
        whatsapp: "",
        phone: "+86 592 8888 6789",
        email: "xia@recovertech.com",
        line: "",
        isPrimary: true,
        isActive: true,
        notes: "",
      },
    ],
  }),
  createSupplier({
    id: "sup-008",
    factoryName: "Suzhou RoboClean Inc.",
    displayName: "RoboClean Suzhou",
    country: "China",
    provinceRegion: "Jiangsu",
    cityDistrict: "Suzhou · Wuzhong",
    mainProductCategory: "Robotics & Cleaning",
    updatedAt: "2026-06-25T13:30:00",
    contacts: [
      {
        contactName: "Sun Hao",
        position: "Project Manager",
        salesRepCode: "RC-078",
        wechatId: "sunhao_robo",
        whatsapp: "+86 135 0013 5008",
        phone: "+86 512 8888 4567",
        email: "hao@roboclean.cn",
        line: "",
        isPrimary: true,
        isActive: true,
        notes: "",
      },
    ],
  }),
  createSupplier({
    id: "sup-009",
    factoryName: "Zhongshan LightWorks Co.",
    displayName: "LightWorks",
    country: "China",
    provinceRegion: "Guangdong",
    cityDistrict: "Zhongshan · Guzhen",
    mainProductCategory: "Lighting",
    updatedAt: "2026-07-01T07:45:00",
    contacts: [
      {
        contactName: "Zheng Min",
        position: "Sales Manager",
        salesRepCode: "LW-212",
        wechatId: "zhengmin_lw",
        whatsapp: "",
        phone: "+86 760 8888 8901",
        email: "min@lightworks.cn",
        line: "",
        isPrimary: true,
        isActive: true,
        notes: "",
      },
    ],
  }),
];

export const SUPPLIER_SEEDS = supplierSeeds;

/** Maps product IDs to supplier master records. */
export const PRODUCT_SUPPLIER_IDS: Record<string, string> = {
  "prod-001": "sup-001",
  "prod-002": "sup-002",
  "prod-003": "sup-003",
  "prod-004": "sup-004",
  "prod-005": "sup-005",
  "prod-006": "sup-006",
  "prod-007": "sup-007",
  "prod-009": "sup-009",
};

export function supplierIdForProduct(productId: string): string | null {
  return PRODUCT_SUPPLIER_IDS[productId] ?? null;
}
