-- Seminar Planner seed from Seminar Planner-1.xlsx
-- Idempotent: seed_key + ON CONFLICT DO NOTHING / NOT EXISTS guards
-- Safe to re-run after a partial failure (rows inserted before an error are skipped)
-- Apply after 20260717120000_seminar_planner.sql and 20260717130000_seminar_planner_rls.sql

insert into public.seminar_lib_target_groups (seed_key, name, description, sort_order, is_active) values ('tg:29-สาขา-fti', '29 สาขา FTI', 'ทีมหน้าร้าน/สาขาภายในทั้งหมด ใช้เพื่อสื่อสารทิศทางเดียวกัน', 1, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_target_groups (seed_key, name, description, sort_order, is_active) values ('tg:vip-dealer', 'VIP Dealer', 'ตัวแทนจำหน่ายยอดสูง/มีอิทธิพล ควรเน้นความสัมพันธ์และสิทธิพิเศษ', 2, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_target_groups (seed_key, name, description, sort_order, is_active) values ('tg:ลูกค้ารายใหญ่ที่ยังไม่เป็นตัวแทน', 'ลูกค้ารายใหญ่ที่ยังไม่เป็นตัวแทน', 'ลูกค้าซื้อเยอะ แต่ยังไม่อยู่ในระบบ Dealer ใช้เพื่อปูทาง Partnership', 3, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_target_groups (seed_key, name, description, sort_order, is_active) values ('tg:dealer-ทั่วไป', 'Dealer ทั่วไป', 'กลุ่มตัวแทนกว้าง เน้นความเข้าใจระบบและโอกาสขาย', 4, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_target_groups (seed_key, name, description, sort_order, is_active) values ('tg:ทีมขายภายใน', 'ทีมขายภายใน', 'Sale/Branch/Key Account ที่ต้องนำสารไปเล่าต่อ', 5, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_target_groups (seed_key, name, description, sort_order, is_active) values ('tg:ผู้บริหารและหัวหน้าสาขา', 'ผู้บริหารและหัวหน้าสาขา', 'กลุ่มตัดสินใจ/วางแผน ให้เน้น Strategy และ Commitment', 6, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_target_groups (seed_key, name, description, sort_order, is_active) values ('tg:supplier-strategic', 'Supplier Strategic', 'Supplier ที่อยากให้ร่วมพัฒนา Product/Support', 7, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_target_groups (seed_key, name, description, sort_order, is_active) values ('tg:mixed-audience', 'Mixed Audience', 'ใช้เมื่องานมีหลายกลุ่มรวมกัน ต้องบาลานซ์ความลึกของเนื้อหา', 8, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_purposes (seed_key, name, description, sort_order, is_active) values ('purpose:อัปเดตทิศทาง-fti', 'อัปเดตทิศทาง FTI', 'สร้างความมั่นใจและภาพเดียวกันก่อนเริ่มปีใหม่', 1, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_purposes (seed_key, name, description, sort_order, is_active) values ('purpose:เตรียมความพร้อมระบบ-membership', 'เตรียมความพร้อมระบบ Membership', 'ให้ผู้ร่วมงานเข้าใจแต้ม Tier และเริ่มวางแผนการซื้อ', 2, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_purposes (seed_key, name, description, sort_order, is_active) values ('purpose:ประชาสัมพันธ์-function-flow', 'ประชาสัมพันธ์ Function Flow', 'สื่อสารระบบ Tracking/Feature ที่จะทยอยเปิดใช้ก่อนเต็มรูปแบบ', 3, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_purposes (seed_key, name, description, sort_order, is_active) values ('purpose:เปิดตัว-ทดลองสินค้าใหม่', 'เปิดตัว/ทดลองสินค้าใหม่', 'ให้จับจริง เห็นจริง วางแผนขายได้ก่อนเปิดขาย', 4, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_purposes (seed_key, name, description, sort_order, is_active) values ('purpose:ดันสินค้า-hidden-gems', 'ดันสินค้า Hidden Gems', 'หยิบสินค้าดีที่ถูกมองข้ามกลับมาสร้างยอด', 5, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_purposes (seed_key, name, description, sort_order, is_active) values ('purpose:รับฟังเสียงสาขาและ-vip', 'รับฟังเสียงสาขาและ VIP', 'เก็บ Insight ปัญหา ความต้องการ และข้อเสนอแนะ', 6, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_purposes (seed_key, name, description, sort_order, is_active) values ('purpose:สร้าง-relationship', 'สร้าง Relationship', 'ทำให้สาขา/VIP รู้สึกเป็นคนวงในและใกล้ผู้บริหาร', 7, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_purposes (seed_key, name, description, sort_order, is_active) values ('purpose:ยกระดับช่องทางการตลาด', 'ยกระดับช่องทางการตลาด', 'สื่อสาร Asset Drive Center, Content, Campaign Support', 8, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_purposes (seed_key, name, description, sort_order, is_active) values ('purpose:สร้าง-action-plan-หลังงาน', 'สร้าง Action Plan หลังงาน', 'ให้ทุกฝ่ายมีสิ่งที่ต้องกลับไปทำต่ออย่างชัดเจน', 9, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:ceo', 'CEO', 'Vision, Direction, Deep Talk, Relationship', 1, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:ผู้บริหารฝ่ายการตลาด', 'ผู้บริหารฝ่ายการตลาด', 'Brand, Campaign, Membership, Asset Drive, Agenda หลัก', 2, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:จัดซื้อ', 'จัดซื้อ', 'Product Roadmap, Supplier, Pricing Logic, New Product Plan', 3, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:r-d', 'R&D', 'Demo, Test, Technical Explanation, Product Validation', 4, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:product-manager', 'Product Manager', 'Hidden Gems, Product Battle, Deep Dive', 5, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:sale-manager', 'Sale Manager', 'How to Sell, Dealer/Branch Strategy', 6, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:branch-manager', 'Branch Manager', 'Best Practice Sharing, Branch Reality', 7, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:it-digital-team', 'IT / Digital Team', 'Function Flow, Tracking, Dashboard, Asset Center', 8, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:service-team', 'Service Team', 'After-sales, Installation, Common Problems', 9, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:vip-dealer-guest', 'VIP Dealer Guest', 'Success Story, Dealer Voice', 10, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:supplier-guest', 'Supplier Guest', 'ใช้เฉพาะ Demo/Tech ไม่ให้พูดยาวขายตัวเอง', 11, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:moderator', 'Moderator', 'คุมเวที Panel, Q&A, Deep Talk', 12, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:ทีม-marketing-content', 'ทีม Marketing Content', 'Asset Drive, Content Template, Social Media', 13, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_speakers (seed_key, name, role_hint, sort_order, is_active) values ('speaker:hr-training', 'HR / Training', 'Ice Breaking, Group Activity, Workshop Support', 14, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:keynote', 'Keynote', '', 1, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:panel', 'Panel', '', 2, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:workshop', 'Workshop', '', 3, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:demo-playground', 'Demo / Playground', '', 4, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:round-table', 'Round Table', '', 5, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:clinic', 'Clinic', '', 6, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:exhibition-zone', 'Exhibition Zone', '', 7, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:award', 'Award', '', 8, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:networking', 'Networking', '', 9, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:break', 'Break', '', 10, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:lunch-dinner', 'Lunch / Dinner', '', 11, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:q-a', 'Q&A', '', 12, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_formats (seed_key, name, description, sort_order, is_active) values ('format:activity-game', 'Activity / Game', '', 13, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_session_statuses (seed_key, name, description, sort_order, is_active) values ('status:idea', 'Idea', '', 1, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_session_statuses (seed_key, name, description, sort_order, is_active) values ('status:draft', 'Draft', '', 2, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_session_statuses (seed_key, name, description, sort_order, is_active) values ('status:need-detail', 'Need Detail', '', 3, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_session_statuses (seed_key, name, description, sort_order, is_active) values ('status:confirmed', 'Confirmed', '', 4, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_session_statuses (seed_key, name, description, sort_order, is_active) values ('status:assigned', 'Assigned', '', 5, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_session_statuses (seed_key, name, description, sort_order, is_active) values ('status:ready', 'Ready', '', 6, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_session_statuses (seed_key, name, description, sort_order, is_active) values ('status:cancel-hold', 'Cancel / Hold', '', 7, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_categories (seed_key, name, description, color_hint, sort_order, is_active) values ('cat:corporate-update', 'Corporate Update', '', '', 1, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_categories (seed_key, name, description, color_hint, sort_order, is_active) values ('cat:product', 'Product', '', '', 2, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_categories (seed_key, name, description, color_hint, sort_order, is_active) values ('cat:membership-digital', 'Membership & Digital', '', '', 3, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_categories (seed_key, name, description, color_hint, sort_order, is_active) values ('cat:sales-marketing', 'Sales & Marketing', '', '', 4, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_categories (seed_key, name, description, color_hint, sort_order, is_active) values ('cat:branch-sharing', 'Branch Sharing', '', '', 5, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_categories (seed_key, name, description, color_hint, sort_order, is_active) values ('cat:voice-of-customer', 'Voice of Customer', '', '', 6, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_categories (seed_key, name, description, color_hint, sort_order, is_active) values ('cat:interactive', 'Interactive', '', '', 7, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_categories (seed_key, name, description, color_hint, sort_order, is_active) values ('cat:recognition', 'Recognition', '', '', 8, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_categories (seed_key, name, description, color_hint, sort_order, is_active) values ('cat:entertainment', 'Entertainment', '', '', 9, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_categories (seed_key, name, description, color_hint, sort_order, is_active) values ('cat:logistics', 'Logistics', '', '', 10, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:corporate-update-opening-welcome', 'Corporate Update', 'Opening & Welcome', 'Keynote', 10, 'Moderator', '[{"id":"b1","text":"เปิดงาน สร้างบรรยากาศ และบอกเป้าหมายของวัน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้ทุกคนเข้าใจว่างานนี้ไม่ใช่แค่ฟังอบรม แต่เป็นการร่วมวางทิศทาง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ผู้ร่วมงานพร้อมเข้าสู่เนื้อหาและเข้าใจภาพรวม","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 1, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:corporate-update-ceo-vision-update', 'Corporate Update', 'CEO Vision Update', 'Keynote', 20, 'CEO', '[{"id":"b1","text":"ผู้บริหารเล่าทิศทาง FTI ช่วงครบรอบ 30 ปี และการเปลี่ยนแปลงปีหน้า","sort_order":0}]'::jsonb, '[{"id":"b1","text":"สร้างความเชื่อมั่นว่า FTI ไม่ได้หยุดนิ่งและพร้อมสนับสนุนทุกช่องทาง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ความเชื่อมั่น/คำถามเชิงกลยุทธ์จากสาขาและ VIP","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 2, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:corporate-update-fti-30-years-journey', 'Corporate Update', 'FTI 30 Years Journey', 'Keynote', 15, 'ผู้บริหารฝ่ายการตลาด', '[{"id":"b1","text":"เล่าเส้นทาง 30 ปีแบบกระชับ เชื่อมอดีตกับอนาคต","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ทำให้คนในและ VIP รู้สึกเป็นส่วนหนึ่งของการเดินทาง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ความภูมิใจร่วมและภาพจำแบรนด์ที่แข็งแรง","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 3, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:corporate-update-business-direction-2027', 'Corporate Update', 'Business Direction 2027', 'Keynote', 20, 'CEO', '[{"id":"b1","text":"สรุปทิศทางธุรกิจ สินค้า ช่องทาง และระบบสนับสนุนปีหน้า","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้สาขาและ VIP เตรียมตัวล่วงหน้า","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Commitment ต่อแผนปีหน้าและคำถามสำคัญ","sort_order":0}]'::jsonb, array['ผู้บริหารและหัวหน้าสาขา']::text[], 4, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:corporate-update-market-outlook-water-trends', 'Corporate Update', 'Market Outlook & Water Trends', 'Keynote', 15, 'Sale Manager', '[{"id":"b1","text":"ภาพรวมตลาดเครื่องกรองน้ำ พฤติกรรมลูกค้า และโอกาสใหม่","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ชี้ให้เห็นว่าตลาดเปลี่ยน และ FTI เตรียมเครื่องมือรองรับ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ประเด็นตลาดที่สาขาเห็นตรง/เห็นต่าง","sort_order":0}]'::jsonb, array['Dealer ทั่วไป']::text[], 5, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:corporate-update-china-watertech-recap', 'Corporate Update', 'China Watertech Recap', 'Keynote', 15, 'จัดซื้อ', '[{"id":"b1","text":"สรุปสิ่งที่ได้จากงานจีน เทรนด์สินค้าใหม่ และแนวทางคัดเลือก","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้เห็นว่า FTI คัดสินค้าแบบมีระบบ ไม่ได้เลือกตามกระแส","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ความสนใจต่อกลุ่มสินค้าใหม่","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 6, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:product-hidden-gems-collection', 'Product', 'Hidden Gems Collection', 'Demo / Playground', 30, 'Product Manager', '[{"id":"b1","text":"แนะนำสินค้าเก่าที่ดีแต่ไม่ค่อยถูกขาย พร้อมเหตุผลว่าทำไมควรหยิบมาขาย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ปลุกสินค้า GP ดี/ปัญหาน้อย/ขายซ้ำได้ ให้กลับมาอยู่ในสายตา","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายชื่อสินค้าที่สาขาอยากทดลองขาย","sort_order":0}]'::jsonb, array['Dealer ทั่วไป']::text[], 7, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:product-new-product-showcase', 'Product', 'New Product Showcase', 'Demo / Playground', 45, 'Product Manager', '[{"id":"b1","text":"เปิดตัวสินค้าใหม่แบบจับจริง เห็นจริง ไม่ใช่ดูสไลด์อย่างเดียว","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ทำให้ผู้ร่วมงานจำจุดขายและข้อจำกัดได้จริง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Feedback ต่อสินค้าใหม่และการตั้งราคา/แพ็กเกจ","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 8, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:product-product-demo-live', 'Product', 'Product Demo Live', 'Demo / Playground', 20, 'R&D', '[{"id":"b1","text":"ทดลองติดตั้ง เปิดเครื่อง แกะชิ้นส่วน หรือทดสอบการใช้งานจริง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"เปลี่ยนความเข้าใจจากฟังเป็นประสบการณ์","sort_order":0}]'::jsonb, '[{"id":"b1","text":"คำถามเทคนิค ปัญหาหน้างาน และจุดที่ต้องทำคู่มือเพิ่ม","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 9, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:product-product-battle', 'Product', 'Product Battle', 'Panel', 20, 'Product Manager', '[{"id":"b1","text":"เทียบสินค้า 2-3 รุ่นแบบพูดข้อดีข้อเสียจริง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ช่วยให้สาขาเลือกสินค้าให้เหมาะกับลูกค้า ไม่ขายผิดตัว","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Use case สำหรับแต่ละรุ่นและคำถามคาใจ","sort_order":0}]'::jsonb, array['ทีมขายภายใน']::text[], 10, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:product-product-deep-dive', 'Product', 'Product Deep Dive', 'Keynote', 30, 'R&D', '[{"id":"b1","text":"เจาะสินค้าเด่นแบบลึกขึ้น เช่น โครงสร้าง ไส้กรอง จุดต่าง และข้อควรระวัง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"สร้างความเข้าใจที่ใช้ตอบลูกค้าหน้างานได้","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ประเด็นที่ต้องทำเป็น FAQ หรือ Asset เพิ่ม","sort_order":0}]'::jsonb, array['ทีมขายภายใน']::text[], 11, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:product-future-product-preview', 'Product', 'Future Product Preview', 'Exhibition Zone', 30, 'จัดซื้อ', '[{"id":"b1","text":"โชว์ Prototype / Demo / Concept ที่ยังไม่ขายจริง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ทำให้ VIP และสาขารู้สึกเป็นวงใน และเก็บเสียงก่อนสั่งจริง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Feedback ก่อนเปิดขายจริง ลดความเสี่ยงการสั่งผิด","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 12, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:product-product-roadmap-2027', 'Product', 'Product Roadmap 2027', 'Keynote', 20, 'จัดซื้อ', '[{"id":"b1","text":"เล่ากลุ่มสินค้าที่จะเน้นปีหน้า และสินค้าที่ควรวางแผนล่วงหน้า","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้สาขา/Dealer เตรียมพื้นที่ขายและงบซื้อ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ความต้องการ pre-order หรือ demo เพิ่ม","sort_order":0}]'::jsonb, array['ผู้บริหารและหัวหน้าสาขา']::text[], 13, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:membership-digital-function-flow-introduction', 'Membership & Digital', 'Function Flow Introduction', 'Keynote', 20, 'ผู้บริหารฝ่ายการตลาด', '[{"id":"b1","text":"แนะนำระบบ Function Flow ว่าจะเป็นศูนย์กลางแต้ม สถานะ และสิทธิประโยชน์","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้ทุกคนเข้าใจว่า FTI กำลังเปลี่ยนจากโปรรายเดือนสู่ระบบระยะยาว","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ความเข้าใจเบื้องต้นและคำถามเรื่องการใช้งาน","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 14, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:membership-digital-membership-roadmap', 'Membership & Digital', 'Membership Roadmap', 'Keynote', 20, 'ผู้บริหารฝ่ายการตลาด', '[{"id":"b1","text":"เล่า Roadmap ว่าระบบจะเต็ม 100% ปีหน้า แต่ทยอยเปิด Feature ก่อน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้ Dealer/VIP เตรียมวางแผนการซื้อ ไม่ต้องรอถึงปีหน้า","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ความพร้อมเข้าร่วม Pilot และคำถามเงื่อนไข","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 15, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:membership-digital-point-system-preview', 'Membership & Digital', 'Point System Preview', 'Keynote', 15, 'ผู้บริหารฝ่ายการตลาด', '[{"id":"b1","text":"อธิบายแต้ม Tier Reward และหลักคิดการสะสมแบบเข้าใจง่าย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ลดความสับสนและทำให้เห็นประโยชน์จากการซื้อสม่ำเสมอ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"คำถามเรื่องแต้ม/เงื่อนไข/ของรางวัล","sort_order":0}]'::jsonb, array['Dealer ทั่วไป']::text[], 16, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:membership-digital-early-access-features', 'Membership & Digital', 'Early Access Features', 'Demo / Playground', 15, 'IT / Digital Team', '[{"id":"b1","text":"โชว์ฟีเจอร์ที่จะทยอยเปิด เช่น Tracking, Status, Dashboard, Claim Reward","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ทำให้คนเห็นว่าระบบกำลังเกิดจริง ไม่ใช่แค่แนวคิด","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายชื่อกลุ่มที่อยากทดลองใช้ก่อน","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 17, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:membership-digital-dealer-dashboard-preview', 'Membership & Digital', 'Dealer Dashboard Preview', 'Demo / Playground', 20, 'IT / Digital Team', '[{"id":"b1","text":"พรีวิวหน้าจอ Dashboard สำหรับดูยอด แต้ม สิทธิ์ และสถานะ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้ผู้ใช้เห็นประโยชน์เชิงปฏิบัติ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Feedback UX และข้อมูลที่อยากเห็นเพิ่ม","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 18, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:membership-digital-asset-drive-center-update', 'Membership & Digital', 'Asset Drive Center Update', 'Demo / Playground', 20, 'ทีม Marketing Content', '[{"id":"b1","text":"อัปเดตศูนย์รวมรูปสินค้า Artwork Template คลิป และเอกสารขาย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้สาขา/Dealer รู้ว่าหา Asset ได้จากที่ไหน ลดงานขอซ้ำ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายการ Asset ที่ต้องเพิ่มและผู้รับผิดชอบ","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 19, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:membership-digital-digital-transformation-journey', 'Membership & Digital', 'Digital Transformation Journey', 'Keynote', 15, 'IT / Digital Team', '[{"id":"b1","text":"เล่าภาพรวมการเปลี่ยนระบบสนับสนุนจาก Manual เป็น Digital","sort_order":0}]'::jsonb, '[{"id":"b1","text":"สร้างความมั่นใจว่า FTI กำลังลดความยุ่งยากให้ช่องทางขาย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Pain point ที่ควรแก้ด้วยระบบในเฟสถัดไป","sort_order":0}]'::jsonb, array['ผู้บริหารและหัวหน้าสาขา']::text[], 20, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:sales-marketing-water-store-growth-strategy', 'Sales & Marketing', 'Water Store Growth Strategy', 'Keynote', 20, 'Sale Manager', '[{"id":"b1","text":"แนวทางใช้ Water Store เป็นจุดสร้างการมองเห็นและลูกค้าใหม่","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้สาขาเห็นบทบาทของหน้าร้านในฐานะสื่อและช่องทางขาย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ไอเดียกิจกรรมหน้าร้าน/พื้นที่ทดลอง","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 21, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:sales-marketing-marketing-support-program', 'Sales & Marketing', 'Marketing Support Program', 'Keynote', 20, 'ผู้บริหารฝ่ายการตลาด', '[{"id":"b1","text":"อธิบายสิ่งที่ FTI จะช่วยช่องทางขาย เช่น Content, Artwork, Campaign, Booth","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้ Dealer รู้ว่าไม่ได้ขายลำพัง และรู้วิธีขอ Support","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ความต้องการสนับสนุนรายสาขา/รายพื้นที่","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 22, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:sales-marketing-content-asset-support', 'Sales & Marketing', 'Content & Asset Support', 'Workshop', 30, 'ทีม Marketing Content', '[{"id":"b1","text":"สอนใช้ภาพ คลิป Caption และ Template ให้ถูกต้องกับแบรนด์","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ลดภาพลักษณ์แตกต่างกัน และทำให้สื่อสารง่ายขึ้น","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายการ Template ที่ทีมต้องทำต่อ","sort_order":0}]'::jsonb, array['Dealer ทั่วไป']::text[], 23, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:sales-marketing-social-media-best-practice', 'Sales & Marketing', 'Social Media Best Practice', 'Workshop', 30, 'ทีม Marketing Content', '[{"id":"b1","text":"แชร์วิธีโพสต์สินค้า/บริการให้ดูน่าเชื่อถือ ไม่ Hard Sell เกินไป","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ยกระดับการตลาดของสาขาและ Dealer","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ตัวอย่างโพสต์/คอนเทนต์ที่นำไปใช้ได้ทันที","sort_order":0}]'::jsonb, array['Dealer ทั่วไป']::text[], 24, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:sales-marketing-campaign-preview', 'Sales & Marketing', 'Campaign Preview', 'Keynote', 15, 'ผู้บริหารฝ่ายการตลาด', '[{"id":"b1","text":"พรีวิวแคมเปญที่ FTI จะสื่อสารต่อสาธารณะ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้สาขาเตรียมรับลูกค้าที่เห็นสื่อและถามกลับมา","sort_order":0}]'::jsonb, '[{"id":"b1","text":"คำถามเรื่องช่วงเวลาและการร่วมโปรโมต","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 25, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:sales-marketing-how-to-sell-more', 'Sales & Marketing', 'How To Sell More', 'Workshop', 45, 'Sale Manager', '[{"id":"b1","text":"เวิร์กช็อปวิธีเลือกสินค้า พูดจุดขาย ปิดการขาย และ Upsell","sort_order":0}]'::jsonb, '[{"id":"b1","text":"เพิ่มทักษะที่เอาไปใช้ขายจริงได้","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Action plan ของแต่ละสาขาหลังงาน","sort_order":0}]'::jsonb, array['ทีมขายภายใน']::text[], 26, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:branch-sharing-branch-best-practice-sharing', 'Branch Sharing', 'Branch Best Practice Sharing', 'Panel', 30, 'Branch Manager', '[{"id":"b1","text":"ให้สาขาที่ทำได้ดีแชร์วิธีทำงานจริง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"แลกเปลี่ยนสิ่งที่พิสูจน์แล้วในสนามจริง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Checklist วิธีทำที่สาขาอื่นนำไปลอง","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 27, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:branch-sharing-fastest-growing-branch', 'Branch Sharing', 'Fastest Growing Branch', 'Keynote', 15, 'Branch Manager', '[{"id":"b1","text":"เล่าเคสสาขาที่เติบโตเร็วว่าทำอะไรต่าง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"สร้างแรงบันดาลใจและมาตรฐานใหม่","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ปัจจัยสำเร็จที่ทำซ้ำได้","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 28, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:branch-sharing-problem-solving-session', 'Branch Sharing', 'Problem Solving Session', 'Clinic', 45, 'Moderator', '[{"id":"b1","text":"หยิบปัญหาจริงจากสาขามาช่วยกันแก้สด","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ทำให้การประชุมมีประโยชน์จริง ไม่ใช่แค่รับฟังจากส่วนกลาง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายการปัญหาและ Owner ที่ต้องกลับไปแก้","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 29, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:branch-sharing-lessons-learned', 'Branch Sharing', 'Lessons Learned', 'Panel', 20, 'Branch Manager', '[{"id":"b1","text":"แชร์สิ่งที่เคยพลาด เพื่อไม่ให้สาขาอื่นพลาดซ้ำ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"สร้างวัฒนธรรมเรียนรู้แบบไม่โทษกัน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ข้อควรระวังและแนวทางป้องกัน","sort_order":0}]'::jsonb, array['ทีมขายภายใน']::text[], 30, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:voice-of-customer-vip-customer-talk', 'Voice of Customer', 'VIP Customer Talk', 'Panel', 30, 'VIP Dealer Guest', '[{"id":"b1","text":"เชิญ VIP/ลูกค้ารายใหญ่พูดมุมมองต่อ FTI และสิ่งที่ต้องการ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้ทีมในฟังเสียงลูกค้าตรงๆ และทำให้ VIP รู้สึกมีคุณค่า","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Insight จากลูกค้ารายใหญ่","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 31, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:voice-of-customer-dealer-panel', 'Voice of Customer', 'Dealer Panel', 'Panel', 45, 'Moderator', '[{"id":"b1","text":"Panel ตัวแทน/VIP พูดเรื่องโอกาส ปัญหา และสิ่งที่อยากให้ FTI ช่วย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ใช้เวทีเป็นการรับฟังอย่างเป็นระบบ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Pain point และ Demand ที่ใช้ทำแผนต่อ","sort_order":0}]'::jsonb, array['Dealer ทั่วไป']::text[], 32, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:voice-of-customer-open-feedback-session', 'Voice of Customer', 'Open Feedback Session', 'Q&A', 30, 'Moderator', '[{"id":"b1","text":"เปิดให้ถาม/เสนอแบบควบคุมเวลา อาจใช้ QR รับคำถาม","sort_order":0}]'::jsonb, '[{"id":"b1","text":"เก็บเสียงจริงโดยไม่ให้เวทีหลุดประเด็น","sort_order":0}]'::jsonb, '[{"id":"b1","text":"คำถาม FAQ และประเด็นเร่งด่วน","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 33, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:voice-of-customer-what-we-need-from-fti', 'Voice of Customer', 'What We Need From FTI', 'Round Table', 45, 'Moderator', '[{"id":"b1","text":"แบ่งโต๊ะพูดคุยว่าช่องทางขายต้องการอะไรจาก FTI","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้ได้ข้อมูลเชิงลึกมากกว่า Q&A หน้าเวที","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายการความต้องการเรียง Priority","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 34, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:interactive-ceo-deep-talk', 'Interactive', 'CEO Deep Talk', 'Round Table', 60, 'CEO', '[{"id":"b1","text":"โต๊ะกลม 4 ที่นั่ง รอบละ 15 นาที ให้คุยกับ CEO/จัดซื้อ/R&D/Marketing","sort_order":0}]'::jsonb, '[{"id":"b1","text":"สร้างความสัมพันธ์ระดับสูงและความรู้สึกเป็นคนวงใน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"คำถาม/ข้อเสนอที่ต้อง Follow up เฉพาะราย","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 35, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:interactive-product-playground', 'Interactive', 'Product Playground', 'Demo / Playground', 60, 'R&D', '[{"id":"b1","text":"พื้นที่ทดลองสินค้าแบบหมุนฐาน ให้ผู้ร่วมงานจับ ลอง ถาม และเทียบได้","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ทำให้สินค้าใหม่ถูกเข้าใจผ่านประสบการณ์","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Feedback หน้างานและคำถามที่ต้องทำสื่อเพิ่ม","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 36, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:interactive-dealer-clinic', 'Interactive', 'Dealer Clinic', 'Clinic', 45, 'Sale Manager', '[{"id":"b1","text":"คลินิกแก้ปัญหาการขาย การตลาด หน้าร้าน หรือบริการแบบเคสต่อเคส","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้ผู้ร่วมงานรู้สึกได้ประโยชน์ตรงกับปัญหาตัวเอง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายการเคสและคำแนะนำเฉพาะราย","sort_order":0}]'::jsonb, array['Dealer ทั่วไป']::text[], 37, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:interactive-ask-me-anything', 'Interactive', 'Ask Me Anything', 'Q&A', 30, 'Moderator', '[{"id":"b1","text":"ถามตอบสดกับผู้บริหาร/ทีมหลักแบบควบคุมประเด็น","sort_order":0}]'::jsonb, '[{"id":"b1","text":"เคลียร์ข้อสงสัยสำคัญก่อนปิดงาน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"FAQ และประเด็นที่ต้องสื่อสารต่อ","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 38, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:recognition-top-dealer-award', 'Recognition', 'Top Dealer Award', 'Award', 20, 'CEO', '[{"id":"b1","text":"มอบรางวัล Dealer/ลูกค้าที่มียอดหรือความร่วมมือโดดเด่น","sort_order":0}]'::jsonb, '[{"id":"b1","text":"สร้างแรงจูงใจและภาพจำบวก","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ภาพ PR และความสัมพันธ์ที่แน่นขึ้น","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 39, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:recognition-branch-achievement-award', 'Recognition', 'Branch Achievement Award', 'Award', 20, 'ผู้บริหารฝ่ายการตลาด', '[{"id":"b1","text":"ยกย่องสาขาที่ทำผลงานดีหรือมีพัฒนาการชัด","sort_order":0}]'::jsonb, '[{"id":"b1","text":"กระตุ้นทีมภายในและสร้างมาตรฐานใหม่","sort_order":0}]'::jsonb, '[{"id":"b1","text":"แรงจูงใจและเคสตัวอย่าง","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 40, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:recognition-long-partnership-award', 'Recognition', 'Long Partnership Award', 'Award', 15, 'CEO', '[{"id":"b1","text":"ขอบคุณผู้ร่วมงานที่อยู่กับ FTI มานาน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รักษาความสัมพันธ์และความภักดี","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ภาพความผูกพันระยะยาว","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 41, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:entertainment-quiz-game', 'Entertainment', 'Quiz Game', 'Activity / Game', 15, 'Moderator', '[{"id":"b1","text":"เกมทบทวนความเข้าใจแบบสนุก เช่น สินค้า/ระบบ/แต้ม","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ทำให้ความรู้ไม่หนักเกินไป และเช็คความเข้าใจ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"คะแนน/ประเด็นที่คนยังเข้าใจผิด","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 42, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:entertainment-lucky-draw', 'Entertainment', 'Lucky Draw', 'Activity / Game', 15, 'Moderator', '[{"id":"b1","text":"จับรางวัลเพื่อสร้างบรรยากาศและตรึงคนไว้จนจบ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"เพิ่มความสนุกและภาพจำของงาน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Engagement และภาพกิจกรรม","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 43, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:entertainment-networking-dinner', 'Entertainment', 'Networking Dinner', 'Lunch / Dinner', 90, 'Moderator', '[{"id":"b1","text":"มื้ออาหารสำหรับคุยต่อแบบไม่เป็นทางการ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"สร้างความสัมพันธ์ที่เวทีใหญ่ทำไม่ได้","sort_order":0}]'::jsonb, '[{"id":"b1","text":"บทสนทนา/ดีล/ประเด็นติดตามหลังงาน","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 44, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:logistics-registration', 'Logistics', 'Registration', 'Break', 30, 'HR / Training', '[{"id":"b1","text":"ลงทะเบียน รับป้ายชื่อ เอกสาร และจัดกลุ่มผู้ร่วมงาน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"เริ่มงานเป็นระบบและเก็บข้อมูลผู้เข้าร่วม","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายชื่อผู้เข้าร่วมจริงและกลุ่มเป้าหมาย","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 45, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:logistics-coffee-break', 'Logistics', 'Coffee Break', 'Break', 15, 'HR / Training', '[{"id":"b1","text":"พักเบรกและให้เดินชมโซนสินค้า/Asset/Membership","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้คนย่อยข้อมูลและสร้างบทสนทนาระหว่างกัน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Feedback ระหว่างพักและการเยี่ยมโซน","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 46, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:logistics-lunch-break', 'Logistics', 'Lunch Break', 'Lunch / Dinner', 60, 'HR / Training', '[{"id":"b1","text":"พักกลางวัน พร้อมเปิดพื้นที่ Exhibition Zone","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ไม่ให้พลังงานตกและเพิ่มเวลาชมบูธ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"จำนวนคนเข้าโซนต่างๆ","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 47, true) on conflict (seed_key) do nothing;
insert into public.seminar_lib_sessions (seed_key, category_name, title, recommended_format, recommended_minutes, recommended_speaker, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, sort_order, is_active) values ('session:logistics-closing-next-step', 'Logistics', 'Closing & Next Step', 'Keynote', 15, 'ผู้บริหารฝ่ายการตลาด', '[{"id":"b1","text":"สรุปสิ่งที่เกิดขึ้น สิ่งที่จะทยอยเปิด และช่องทางติดตามหลังงาน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ปิดงานด้วย Action ไม่ใช่จบแล้วหาย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายการ Follow-up, Owner, Timeline","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 48, true) on conflict (seed_key) do nothing;

-- FTI CONNECT 2026 sample event (from Agenda Planner sheet)
insert into public.seminar_events (
  seed_key, title, event_type, start_date, end_date, venue, event_format, owner, status, notes, is_archived
) values (
  'event:fti-connect-2026', 'FTI CONNECT 2026', 'สัมมนา / อีเวนต์', '2026-09-07', '2026-09-07', 'FTI', 'on_site', 'ทีมการตลาด', 'planning', '', false
) on conflict (seed_key) do nothing;

insert into public.seminar_event_target_groups (event_id, target_group_id)
select e.id, tg.id
from public.seminar_events e
cross join public.seminar_lib_target_groups tg
where e.seed_key = 'event:fti-connect-2026'
  and tg.name = 'Dealer ทั่วไป'
  and not exists (
    select 1 from public.seminar_event_target_groups x
    where x.event_id = e.id and x.target_group_id = tg.id
  );

insert into public.seminar_event_purposes (event_id, purpose_id)
select e.id, p.id
from public.seminar_events e
cross join public.seminar_lib_purposes p
where e.seed_key = 'event:fti-connect-2026'
  and p.name = 'อัปเดตทิศทาง FTI'
  and not exists (
    select 1 from public.seminar_event_purposes x
    where x.event_id = e.id and x.purpose_id = p.id
  );

insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:1', e.id, 1, 'Registration', 'Logistics', 'Break', '2026-09-07', '15:42', '16:12', 30, 'ทีม Marketing Content', 'Confirmed', '[{"id":"b1","text":"ลงทะเบียน รับป้ายชื่อ เอกสาร และจัดกลุ่มผู้ร่วมงาน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"เริ่มงานเป็นระบบและเก็บข้อมูลผู้เข้าร่วม","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายชื่อผู้เข้าร่วมจริงและกลุ่มเป้าหมาย","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 'ลงทะเบียน + แจก QR/เอกสาร/แผนผังโซน', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:1'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:2', e.id, 2, 'Opening & Welcome', 'Corporate Update', 'Keynote', '2026-09-07', '16:12', '16:22', 10, 'Moderator', 'Confirmed', '[{"id":"b1","text":"เปิดงาน สร้างบรรยากาศ และบอกเป้าหมายของวัน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้ทุกคนเข้าใจว่างานนี้ไม่ใช่แค่ฟังอบรม แต่เป็นการร่วมวางทิศทาง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ผู้ร่วมงานพร้อมเข้าสู่เนื้อหาและเข้าใจภาพรวม","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 'เปิดกรอบงานว่าเป็น Experience ไม่ใช่สัมมนานั่งฟัง', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:2'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:3', e.id, 3, 'CEO Vision Update', 'Corporate Update', 'Keynote', '2026-09-07', '16:22', '16:42', 20, 'CEO', 'Confirmed', '[{"id":"b1","text":"ผู้บริหารเล่าทิศทาง FTI ช่วงครบรอบ 30 ปี และการเปลี่ยนแปลงปีหน้า","sort_order":0}]'::jsonb, '[{"id":"b1","text":"สร้างความเชื่อมั่นว่า FTI ไม่ได้หยุดนิ่งและพร้อมสนับสนุนทุกช่องทาง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ความเชื่อมั่น/คำถามเชิงกลยุทธ์จากสาขาและ VIP","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 'ช่วงสร้างความมั่นใจ ควรเก็บภาพ PR', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:3'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:4', e.id, 4, 'Membership Roadmap', 'Membership & Digital', 'Keynote', '2026-09-07', '16:42', '17:02', 20, 'ผู้บริหารฝ่ายการตลาด', 'Confirmed', '[{"id":"b1","text":"เล่า Roadmap ว่าระบบจะเต็ม 100% ปีหน้า แต่ทยอยเปิด Feature ก่อน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้ Dealer/VIP เตรียมวางแผนการซื้อ ไม่ต้องรอถึงปีหน้า","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ความพร้อมเข้าร่วม Pilot และคำถามเงื่อนไข","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 'เน้นว่า 100% ปีหน้า แต่ทยอยเปิดฟีเจอร์ให้ลองก่อน', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:4'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:5', e.id, 5, 'Asset Drive Center Update', 'Membership & Digital', 'Demo / Playground', '2026-09-07', '17:02', '17:22', 20, 'ทีม Marketing Content', 'Confirmed', '[{"id":"b1","text":"อัปเดตศูนย์รวมรูปสินค้า Artwork Template คลิป และเอกสารขาย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้สาขา/Dealer รู้ว่าหา Asset ได้จากที่ไหน ลดงานขอซ้ำ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายการ Asset ที่ต้องเพิ่มและผู้รับผิดชอบ","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 'สาธิตวิธีช่วยสาขา/Dealer ใช้รูปและสื่อขาย', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:5'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:6', e.id, 6, 'Coffee Break', 'Logistics', 'Break', '2026-09-07', '17:22', '17:37', 15, 'ทีม Marketing Content', 'Confirmed', '[{"id":"b1","text":"พักเบรกและให้เดินชมโซนสินค้า/Asset/Membership","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้คนย่อยข้อมูลและสร้างบทสนทนาระหว่างกัน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Feedback ระหว่างพักและการเยี่ยมโซน","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 'ให้เดินดู Membership Zone / Product Zone', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:6'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:7', e.id, 7, 'Hidden Gems Collection', 'Product', 'Demo / Playground', '2026-09-07', '17:37', '18:07', 30, 'Product Manager', 'Confirmed', '[{"id":"b1","text":"แนะนำสินค้าเก่าที่ดีแต่ไม่ค่อยถูกขาย พร้อมเหตุผลว่าทำไมควรหยิบมาขาย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ปลุกสินค้า GP ดี/ปัญหาน้อย/ขายซ้ำได้ ให้กลับมาอยู่ในสายตา","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายชื่อสินค้าที่สาขาอยากทดลองขาย","sort_order":0}]'::jsonb, array['Dealer ทั่วไป']::text[], 'เลือกสินค้า 5-8 ตัวพอ อย่าเยอะเกิน', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:7'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:8', e.id, 8, 'Hidden Gems Collection', 'Product', 'Demo / Playground', '2026-09-07', '18:07', '18:52', 45, 'Product Manager', 'Confirmed', '[{"id":"b1","text":"แนะนำสินค้าเก่าที่ดีแต่ไม่ค่อยถูกขาย พร้อมเหตุผลว่าทำไมควรหยิบมาขาย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ปลุกสินค้า GP ดี/ปัญหาน้อย/ขายซ้ำได้ ให้กลับมาอยู่ในสายตา","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายชื่อสินค้าที่สาขาอยากทดลองขาย","sort_order":0}]'::jsonb, array['Dealer ทั่วไป']::text[], 'สินค้าใหม่ต้องจับได้/เห็นจริง', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:8'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:9', e.id, 9, 'Lunch Break', 'Logistics', 'Lunch / Dinner', '2026-09-07', '18:52', '19:52', 60, 'ทีม Marketing Content', 'Confirmed', '[{"id":"b1","text":"พักกลางวัน พร้อมเปิดพื้นที่ Exhibition Zone","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ไม่ให้พลังงานตกและเพิ่มเวลาชมบูธ","sort_order":0}]'::jsonb, '[{"id":"b1","text":"จำนวนคนเข้าโซนต่างๆ","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 'เปิด Exhibition Zone ระหว่างพัก', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:9'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:10', e.id, 10, 'Product Playground', 'Interactive', 'Demo / Playground', '2026-09-07', '19:52', '20:52', 60, 'R&D', 'Confirmed', '[{"id":"b1","text":"พื้นที่ทดลองสินค้าแบบหมุนฐาน ให้ผู้ร่วมงานจับ ลอง ถาม และเทียบได้","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ทำให้สินค้าใหม่ถูกเข้าใจผ่านประสบการณ์","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Feedback หน้างานและคำถามที่ต้องทำสื่อเพิ่ม","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 'หมุนฐานทดลองสินค้า', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:10'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:11', e.id, 11, 'Problem Solving Session', 'Branch Sharing', 'Clinic', '2026-09-07', '20:52', '21:22', 30, 'Moderator', 'Confirmed', '[{"id":"b1","text":"หยิบปัญหาจริงจากสาขามาช่วยกันแก้สด","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ทำให้การประชุมมีประโยชน์จริง ไม่ใช่แค่รับฟังจากส่วนกลาง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายการปัญหาและ Owner ที่ต้องกลับไปแก้","sort_order":0}]'::jsonb, array['29 สาขา FTI']::text[], 'เลือก VIP ที่พูดเป็นประโยชน์และสร้างแรงบันดาลใจ', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:11'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:12', e.id, 12, 'Coffee Break', 'Logistics', 'Break', '2026-09-07', '21:22', '21:37', 15, 'ทีม Marketing Content', 'Confirmed', '[{"id":"b1","text":"พักเบรกและให้เดินชมโซนสินค้า/Asset/Membership","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ให้คนย่อยข้อมูลและสร้างบทสนทนาระหว่างกัน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Feedback ระหว่างพักและการเยี่ยมโซน","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 'ใช้เคสจริงจากสาขา', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:12'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:13', e.id, 13, 'New Product Showcase', 'Product', 'Demo / Playground', '2026-09-07', '21:27', '22:27', 60, 'Product Manager', 'Confirmed', '[{"id":"b1","text":"เปิดตัวสินค้าใหม่แบบจับจริง เห็นจริง ไม่ใช่ดูสไลด์อย่างเดียว","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ทำให้ผู้ร่วมงานจำจุดขายและข้อจำกัดได้จริง","sort_order":0}]'::jsonb, '[{"id":"b1","text":"Feedback ต่อสินค้าใหม่และการตั้งราคา/แพ็กเกจ","sort_order":0}]'::jsonb, array['VIP Dealer']::text[], 'รอบละ 15 นาที 4 รอบ', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:13'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:14', e.id, 14, 'Ask Me Anything', 'Interactive', 'Q&A', '2026-09-07', '22:27', '22:57', 30, 'Moderator', 'Confirmed', '[{"id":"b1","text":"ถามตอบสดกับผู้บริหาร/ทีมหลักแบบควบคุมประเด็น","sort_order":0}]'::jsonb, '[{"id":"b1","text":"เคลียร์ข้อสงสัยสำคัญก่อนปิดงาน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"FAQ และประเด็นที่ต้องสื่อสารต่อ","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 'สรุปสิ่งที่จะทยอยเปิด + follow-up', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:14'
  );
insert into public.seminar_agenda_items (seed_key, event_id, sort_order, title, category_name, format_name, session_date, start_time, end_time, duration_minutes, primary_speaker, status_name, detail_bullets, objectives_bullets, outcomes_bullets, target_group_names, team_notes, owner_name)
select
  'agenda:fti-connect-2026:15', e.id, 15, 'Closing & Next Step', 'Logistics', 'Keynote', '2026-09-07', '22:42', '23:12', 30, 'ผู้บริหารฝ่ายการตลาด', 'Confirmed', '[{"id":"b1","text":"สรุปสิ่งที่เกิดขึ้น สิ่งที่จะทยอยเปิด และช่องทางติดตามหลังงาน","sort_order":0}]'::jsonb, '[{"id":"b1","text":"ปิดงานด้วย Action ไม่ใช่จบแล้วหาย","sort_order":0}]'::jsonb, '[{"id":"b1","text":"รายการ Follow-up, Owner, Timeline","sort_order":0}]'::jsonb, array['Mixed Audience']::text[], 'ใช้เฉพาะถ้างานเป็นครึ่งวันบ่ายถึงเย็น', ''
from public.seminar_events e
where e.seed_key = 'event:fti-connect-2026'
  and not exists (
    select 1 from public.seminar_agenda_items a
    where a.seed_key = 'agenda:fti-connect-2026:15'
  );

notify pgrst, 'reload schema';